spring:
  application:
    name: zuul-server
server:
  port: 5555

#对应服务注册中心的配置内容，指定服务注册中心的位置。
eureka:
  client:
   serviceUrl:
    defaultZone: http://admin:123456@localhost:8761/eureka/


#zuul:
#  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: PROVIDE-SERVICE
#    api-b:
#      path: /api-b/**
#      serviceId: FEIGN-SERVER

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000














